import Head from 'next/head'
import imgCover from '@/assets/images/pexels-digital-buggu-172872.jpg'
import LayoutWithHeader from '@/layouts/LayoutWithHeader'
import ContactCard from '@/components/ContactCard'
import ContactCardsSection from '@/components/ContactCardsSection'

const HOTELS = [
  { name: "Hotel Leicam", address: "Praça Guilherme Tito de Azevedo, 45, Centro.", phone: "(22) 2758-1278" },
  { name: "São Fidélis Palace Hotel", address: "Praça Guilherme Tito de Azevedo, 55, Centro.", phone: "(22) 2758-2240" },
  { name: "Solar Hotel", address: "Rua Doutor Faria Serra, 17, Centro.", phone: "(22) 2758-6538" },
  { name: "Hotel São José", address: "Praça São Fidélis, 214, Centro.", phone: "(22) 2758-2428" },
  { name: "Pousada Beira Rio", address: "Rua Emídio Maia Santos, 1386, Vila dos Coroados.", phone: "(22) 2758-2075" },
  { name: "Pousada Clube Cachoeira do Salto", address: "Rua Emídio Maia Santos, 1500, Vila dos Coroados.", phone: "(22) 2758-5871" },
  { name: "Pousada Pureza", address: "Av. Jacy Nader, 411, Pureza.", phone: "(22) 2751-1218" }
]

export default function Hotelaria() {
  return (
    <>
      <Head>
        <title>Hotelaria | Conheça São Fidélis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutWithHeader coverImg={imgCover} title="Hotelaria">
        <ContactCardsSection>
          {HOTELS.map(hotel =>
            <ContactCard
              key={hotel.name}
              title={hotel.name}
              address={hotel.address}
              phone={hotel.phone}
            />
          )}
        </ContactCardsSection>
      </LayoutWithHeader>
    </>
  )
}
